name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v3
      - uses: janole/select-docker-version@main
        with:
          version: '23'
      - run: docker version | grep -i -m 1 Version
